-- MySQL Script generated by MySQL Workbench
-- 06/27/14 14:45:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gmu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gmu` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gmu` ;

-- -----------------------------------------------------
-- Table `gmu`.`Collaborateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Collaborateur` (
  `idCollaborateur` INT NOT NULL AUTO_INCREMENT,
  `nomCollaborateur` VARCHAR(45) NULL,
  `prenomCollaborateur` VARCHAR(45) NULL,
  `numeroAVS` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `sexe` BINARY NULL,
  `anneeArrivee` VARCHAR(45) NULL,
  `anneeDepart` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  `taille` CHAR NULL,
  `veste` BINARY NULL,
  `numeroCompte` VARCHAR(45) NULL,
  `typePaiement` VARCHAR(45) NULL,
  `aUneCle` BINARY NULL,
  PRIMARY KEY (`idCollaborateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmu`.`Evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Evenement` (
  `idEvenement` INT NOT NULL AUTO_INCREMENT,
  `dateEvenement` DATE NOT NULL,
  `heureDebut` TIMESTAMP NULL,
  `heureFin` TIMESTAMP NULL,
  `commentaire` TEXT NULL,
  PRIMARY KEY (`idEvenement`, `dateEvenement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmu`.`Poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Poste` (
  `idPoste` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `montantPoste` INT NULL,
  `Collaborateur_idCollaborateur` INT NOT NULL,
  PRIMARY KEY (`idPoste`, `description`, `Collaborateur_idCollaborateur`),
  INDEX `fk_Poste_Collaborateur1_idx` (`Collaborateur_idCollaborateur` ASC),
  CONSTRAINT `fk_Poste_Collaborateur1`
    FOREIGN KEY (`Collaborateur_idCollaborateur`)
    REFERENCES `gmu`.`Collaborateur` (`idCollaborateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmu`.`Lieu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Lieu` (
  `idLieu` INT NOT NULL AUTO_INCREMENT,
  `nomLieu` VARCHAR(45) NOT NULL,
  `montantVoiture` INT NULL,
  `montantEvenement` INT NULL,
  `Evenement_idEvenement` INT NOT NULL,
  `Evenement_dateEvenement` DATE NOT NULL,
  `Poste_idPoste` INT NOT NULL,
  `Poste_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLieu`, `nomLieu`, `Evenement_idEvenement`, `Evenement_dateEvenement`, `Poste_idPoste`, `Poste_description`),
  INDEX `fk_Lieu_Evenement1_idx` (`Evenement_idEvenement` ASC, `Evenement_dateEvenement` ASC),
  INDEX `fk_Lieu_Poste1_idx` (`Poste_idPoste` ASC, `Poste_description` ASC),
  CONSTRAINT `fk_Lieu_Evenement1`
    FOREIGN KEY (`Evenement_idEvenement` , `Evenement_dateEvenement`)
    REFERENCES `gmu`.`Evenement` (`idEvenement` , `dateEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lieu_Poste1`
    FOREIGN KEY (`Poste_idPoste` , `Poste_description`)
    REFERENCES `gmu`.`Poste` (`idPoste` , `description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmu`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `nomEquipe` VARCHAR(45) NOT NULL,
  `aRisque` BINARY NULL,
  PRIMARY KEY (`idEquipe`, `nomEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmu`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Participation` (
  `Collaborateur_idCollaborateur` INT NOT NULL,
  `Evenement_idEvenement` INT NOT NULL,
  `Evenement_dateEvenement` DATE NOT NULL,
  PRIMARY KEY (`Collaborateur_idCollaborateur`, `Evenement_idEvenement`, `Evenement_dateEvenement`),
  INDEX `fk_Collaborateur_has_Evenement_Evenement1_idx` (`Evenement_idEvenement` ASC, `Evenement_dateEvenement` ASC),
  INDEX `fk_Collaborateur_has_Evenement_Collaborateur_idx` (`Collaborateur_idCollaborateur` ASC),
  CONSTRAINT `fk_Collaborateur_has_Evenement_Collaborateur`
    FOREIGN KEY (`Collaborateur_idCollaborateur`)
    REFERENCES `gmu`.`Collaborateur` (`idCollaborateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collaborateur_has_Evenement_Evenement1`
    FOREIGN KEY (`Evenement_idEvenement` , `Evenement_dateEvenement`)
    REFERENCES `gmu`.`Evenement` (`idEvenement` , `dateEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gmu`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmu`.`Match` (
  `Evenement_idEvenement` INT NOT NULL,
  `Evenement_dateEvenement` DATE NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Equipe_nomEquipeA` VARCHAR(45) NOT NULL,
  `Equipe_nomEquipeB` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Evenement_idEvenement`, `Evenement_dateEvenement`, `Equipe_idEquipe`, `Equipe_nomEquipeA`, `Equipe_nomEquipeB`),
  INDEX `fk_Evenement_has_Equipe_Equipe1_idx` (`Equipe_idEquipe` ASC, `Equipe_nomEquipeA` ASC),
  INDEX `fk_Evenement_has_Equipe_Evenement1_idx` (`Evenement_idEvenement` ASC, `Evenement_dateEvenement` ASC),
  CONSTRAINT `fk_Evenement_has_Equipe_Evenement1`
    FOREIGN KEY (`Evenement_idEvenement` , `Evenement_dateEvenement`)
    REFERENCES `gmu`.`Evenement` (`idEvenement` , `dateEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evenement_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe` , `Equipe_nomEquipeA`)
    REFERENCES `gmu`.`Equipe` (`idEquipe` , `nomEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
